micronaut:
  application:
    name: xivgear-data-api
  server:
    cors:
      enabled: true
  openapi:
    enabled: true
    config:
      property-naming-strategy: gg.xp.xivgear.dataapi.serialization.CapitalizedPropertyNamingStrategy
  swagger:
    enabled: true
    config:
      property-naming-strategy: gg.xp.xivgear.dataapi.serialization.CapitalizedPropertyNamingStrategy
  swagger-ui:
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  object-storage:
    default-bucket: ${OBJECT_STORAGE_BUCKET_NAME:xivgear-data}
    local:
      default:
        enabled: true
        path: ${LOCAL_STORAGE_DIR:persistence}


  jackson:
    enabled: true
  serde:
    enabled: false
  http:
    services:
      - id: json
        json-mapper: jackson

xivapi:
  baseUri: https://bm.xivgear.app/api/1
