micronaut:
  application:
    name: xivgear-data-api
  server:
    cors:
      enabled: true
  openapi:
    enabled: true
    config:
      property-naming-strategy: gg.xp.xivgear.dataapi.serialization.CapitalizedPropertyNamingStrategy
  swagger:
    enabled: true
    config:
      property-naming-strategy: gg.xp.xivgear.dataapi.serialization.CapitalizedPropertyNamingStrategy
  swagger-ui:
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
