micronaut:
  environment:
    name: prodoci

  object-storage:
    default-bucket: ${OBJECT_STORAGE_BUCKET_NAME:xivgear-data}
    oracle-cloud:
      default:
        enabled: true
        bucket: ${OBJECT_STORAGE_BUCKET_NAME:xivgear-data}
        namespace: ${ORACLE_CLOUD_OBJECT_STORAGE_NAMESPACE:}
        compartment-id: ${ORACLE_CLOUD_COMPARTMENT_ID:}
        auth:
    local:
      default:
        enabled: false

oci:
#  config:
#    instance-principal:
#      enabled: false

  tenant-id: ${ORACLE_CLOUD_TENANT_ID:}
  user-id: ${ORACLE_CLOUD_USER_ID:}
  fingerprint: ${ORACLE_CLOUD_FINGERPRINT:}
  private-key-file: file:${ORACLE_CLOUD_PEM_PATH:}
  region: ${ORACLE_CLOUD_OBJECT_STORAGE_REGION:}
